Dependències necessàries

```{r}
library(SmartEDA)
```

Carreguem les dades:
```{r}
df <- read.csv("C:/Users/User/Documents/universitat/2n1q/me/projecte/practicaME/clean-data.csv")
```


Exploració amb diferents informes de la llibreria SmartEDA
```{r}
# Sense objectiu (informe general)
ExpReport(data = df, Target = NULL, op_file = "eda_general.html")

# Amb objectiu categòric
ExpReport(data = df, Target = "Target", op_file = "eda_obj_categ.html", Rc = NULL)
```
Resums numèrics globals
Calcula estadístics univariants per a totes les numèriques sense objectiu, incloent quantils, asimetria/curtosi i outliers.
```{r}
num_sum <- ExpNumStat(
  data = df,
  by = "A",                 # Global (sense estratificar)
  Qnt = seq(0, 1, 0.25),    # Quartils (ajusta si vols decils, etc.)
  MesofShape = 2,           # Inclou asimetria i curtosi
  Outlier = TRUE,           # Detecció d’outliers (basat en boxplot)
  round = 2
)
num_sum
```
Resums categòrics globals
Calcula estadístics univariants per a totes les categòriques.
```{r}
cat_tab <- ExpCTable(
  data = df,
  Target = NULL,    # sense objectiu
  per = TRUE,       # percentatges
  margin = 1,       # 1 = percentatges per fila en taules creuades; per simples no afecta
  clim = 10,        # màxim de nivells a mostrar
  nlim = 3,         # variables amb <= nlim valors únics es tracten com a factors
  round = 2
)
```
