# Model 1 fit
```{r}
# Carreguem les dades
library(readr)
data <- read_csv("../preprocessing/clean-data.csv", col_types = cols(
    Marital_status = col_character(),
    Application_mode = col_character(),
    Application_order = col_integer(),
    Course = col_character(),
    Daytime_evening_attendance = col_character(),
    Previous_qualification = col_character(),
    Previous_qualification_grade = col_double(),
    Nacionality = col_character(),
    Mother_s_qualification = col_integer(),
    Father_s_qualification = col_integer(),
    Mother_s_occupation = col_character(),
    Father_s_occupation = col_character(),
    Admission_grade = col_double(),
    Displaced = col_integer(),
    Educational_special_needs = col_integer(),
    Debtor = col_integer(),
    Tuition_fees_up_to_date = col_integer(),
    Gender = col_integer(),
    Scholarship_holder = col_integer(),
    Age_at_enrollment = col_integer(),
    International = col_integer(),
    Curricular_units_1st_sem_credited = col_integer(),
    Curricular_units_1st_sem_enrolled = col_integer(),
    Curricular_units_1st_sem_evaluations = col_integer(),
    Curricular_units_1st_sem_approved = col_integer(),
    Curricular_units_1st_sem_grade = col_double(),
    Curricular_units_1st_sem_without_evaluations = col_integer(),
    Curricular_units_2nd_sem_credited = col_integer(),
    Curricular_units_2nd_sem_enrolled = col_integer(),
    Curricular_units_2nd_sem_evaluations = col_integer(),
    Curricular_units_2nd_sem_approved = col_integer(),
    Curricular_units_2nd_sem_grade = col_double(),
    Curricular_units_2nd_sem_without_evaluations = col_integer(),
    Unemployment_rate = col_double(),
    Inflation_rate = col_double(),
    GDP = col_double(),
    Target = col_character()
  )
)
```

```{r}
# Descriptiva previa de la variable a estudiar (Admission_grade)
summary(data$Admission_grade)
hist(data$Admission_grade)
```

```{r}
# Construim un mlgz sobre la variable a estudiar
model <- glm(Admission_grade ~ . - Target, data = data, family = gaussian())
summary(model)
```

```{r}
# Construim un model reduit, eliminant variables redundants
model_step <- step(model, direction = "both")
```

```{r}
summary(model_step)
```

```{r}
library(car)
residualPlot(model_step)
```

```{r}
influencePlot(model = model_step)
```

# Construim un model model_polinomic
```{r}
model_poly <- glm(
  Admission_grade ~ 
    # Numèriques polinòmiques
    Previous_qualification_grade + I(Previous_qualification_grade^2) +
    Age_at_enrollment + I(Age_at_enrollment^2) +
    Curricular_units_1st_sem_evaluations + I(Curricular_units_1st_sem_evaluations^2) +
    Curricular_units_1st_sem_grade + I(Curricular_units_1st_sem_grade^2) +
    Unemployment_rate + I(Unemployment_rate^2) +
    
    # Numèriques lineals menys significatives
    Inflation_rate + GDP +
    
    # Categòriques significatives
    Application_mode + Application_order + 
    Course + Previous_qualification + Father_s_qualification,
    
  data = data,
  family = gaussian(link = "identity")
)
```

```{r}
library(car)
residualPlot(model_poly)
```

```{r}

model_poly_gamma <- glm(
  Admission_grade ~ 
    Previous_qualification_grade + I(Previous_qualification_grade^2) +
    Age_at_enrollment + I(Age_at_enrollment^2) +
    Curricular_units_1st_sem_evaluations + I(Curricular_units_1st_sem_evaluations^2) +
    Curricular_units_1st_sem_grade + I(Curricular_units_1st_sem_grade^2) +
    Unemployment_rate + I(Unemployment_rate^2) +
    Inflation_rate + GDP +
    Application_mode + Application_order + Course + Previous_qualification + Father_s_qualification,
  data = data,
  family = quasipoisson(link = "log")
)
```

```{r}
residualPlot(model_poly_gamma)
```