---
title: "Binary Response"
output: "html_document"
date: "15/10/2025"
---


# Model 1 fit
```{r}
# Carreguem les dades
library(readr)
data <- read_csv("preprocessing/clean-data.csv")
```

```{r}
# Descriptiva previa de la variable a estudiar (Admission_grade)
summary(data$Binary_response)
table(data$Binary_response) 
barplot(table(data$Binary_response))
``` 
```{r}
# Construim un mlgz sobre la variable a estudiar
model <- glm(Binary_response ~ . - Target, data = data, family = binomial())
summary(model)
```
```{r}
# Construim el model nul
model_nul <- glm(Binary_response ~ 1, data = data, family = binomial)
```
```{r}
# Comparem el nostre model complet amb el model nul
anova(model, model_nul, test = "Chisq")
```
```{r}
# Construim un model reduit, eliminant les variables poc significatives
model2 <- glm(
    Binary_response ~ 
        Course + 
        Curricular_units_1st_sem_credited + 
        Curricular_units_1st_sem_enrolled + 
        Curricular_units_1st_sem_evaluations + 
        Curricular_units_1st_sem_approved + 
        Curricular_units_2nd_sem_approved + 
        Curricular_units_2nd_sem_grade + 
        Mother_s_occupation + 
        Admission_grade,
    data = data, family = binomial
    )
summary(model2)
```
```{r}
# Comparem el nou model amb el model nul, per veure si hi ha diferència significativa
anova(model, model2, test = "Chisq")
```

