---
title: "Numerical Response"
output: "html_document"
date: "15/10/2025"
---


# Model 1 fit
```{r}
# Carreguem les dades
library(readr)
data <- read_csv("../preprocessing/clean-data.csv", col_types = cols(
    Marital_status = col_character(),
    Application_mode = col_character(),
    Application_order = col_integer(),
    Course = col_character(),
    Daytime_evening_attendance = col_character(),
    Previous_qualification = col_character(),
    Previous_qualification_grade = col_double(),
    Nacionality = col_character(),
    Mother_s_qualification = col_integer(),
    Father_s_qualification = col_integer(),
    Mother_s_occupation = col_character(),
    Father_s_occupation = col_character(),
    Admission_grade = col_double(),
    Displaced = col_integer(),
    Educational_special_needs = col_integer(),
    Debtor = col_integer(),
    Tuition_fees_up_to_date = col_integer(),
    Gender = col_integer(),
    Scholarship_holder = col_integer(),
    Age_at_enrollment = col_integer(),
    International = col_integer(),
    Curricular_units_1st_sem_credited = col_integer(),
    Curricular_units_1st_sem_enrolled = col_integer(),
    Curricular_units_1st_sem_evaluations = col_integer(),
    Curricular_units_1st_sem_approved = col_integer(),
    Curricular_units_1st_sem_grade = col_double(),
    Curricular_units_1st_sem_without_evaluations = col_integer(),
    Curricular_units_2nd_sem_credited = col_integer(),
    Curricular_units_2nd_sem_enrolled = col_integer(),
    Curricular_units_2nd_sem_evaluations = col_integer(),
    Curricular_units_2nd_sem_approved = col_integer(),
    Curricular_units_2nd_sem_grade = col_double(),
    Curricular_units_2nd_sem_without_evaluations = col_integer(),
    Unemployment_rate = col_double(),
    Inflation_rate = col_double(),
    GDP = col_double(),
    Target = col_character()
  )
)
```

```{r}
# Descriptiva previa de la variable a estudiar (Admission_grade)
summary(data$Curricular_units_1st_sem_grade)
hist(data$Curricular_units_1st_sem_grade)
```

```{r}
# Construim un mlgz sobre la variable a estudiar
model <- glm(Curricular_units_1st_sem_grade ~ . - Target, data = data, family = gaussian())
summary(model)
```

```{r}
# Construim el model nul
model_nul <- glm(Curricular_units_1st_sem_grade ~ 1, data = data, family = gaussian)

```

```{r}
# Comparem el nostre model complet amb el model nul
anova(model, model_nul, test = "Chisq")
```

```{r}
# Construim un model reduit, eliminant les variables poc significatives
model2 <- glm(
  Curricular_units_1st_sem_grade ~ 
    Course + 
    Curricular_units_1st_sem_credited + 
    Curricular_units_1st_sem_enrolled + 
    Curricular_units_1st_sem_evaluations + 
    Curricular_units_1st_sem_approved + 
    Curricular_units_2nd_sem_approved + 
    Curricular_units_2nd_sem_grade + 
    Mother_s_occupation + 
    Admission_grade,
  data = data, family = gaussian
)
summary(model2)
```

```{r}
# Comparem el nou model amb el model nul, per veure si hi ha diferència significativa
anova(model, model2, test = "Chisq")
```

```{r}
# Comparem el nou model amb el model complet
anova(model, model2, test = "Chisq")
```

```{r}
# Afegim variables al model reduit (utilitzem la comanda step)
model_step <- step(model, direction = "both")
summary(model_step)
```

```{r}
# Comparem el model step amb el model complet
anova(model, model_step, test = "Chisq")
```

# Model validation
```{r}
library(car)
residualPlot(model_step)
```

```{r}
library(car)
residualPlots(model_step)
```

```{r}
influencePlot(model = model_step)
```

```{r}
vif(model_step)
```

```{r}
# Seleccionar variables numèriques correlacionades
vars_pca <- data[, c(
  'Curricular_units_1st_sem_credited',
  'Curricular_units_1st_sem_enrolled',
  'Curricular_units_1st_sem_evaluations',
  'Curricular_units_1st_sem_approved',
  'Curricular_units_2nd_sem_approved',
  'Curricular_units_2nd_sem_grade',
  'Curricular_units_2nd_sem_enrolled'
)]
```

```{r}
# Fer PCA amb escalat
pca_result <- prcomp(vars_pca, center = TRUE, scale. = TRUE)

# Veure resum de variància explicada
summary(pca_result)
```

```{r}
model_polinomic <- glm(
  Curricular_units_1st_sem_grade ~ 
    Course +
    Previous_qualification +
    Previous_qualification_grade +
    Admission_grade + I(Admission_grade^2) +
    Age_at_enrollment + I(Age_at_enrollment^2) +
    Curricular_units_1st_sem_credited + I(Curricular_units_1st_sem_credited^2) +
    Curricular_units_1st_sem_enrolled + I(Curricular_units_1st_sem_enrolled^2) +
    Curricular_units_1st_sem_evaluations + I(Curricular_units_1st_sem_evaluations^2) +
    Curricular_units_1st_sem_approved + I(Curricular_units_1st_sem_approved^2) +
    Curricular_units_2nd_sem_enrolled + I(Curricular_units_2nd_sem_enrolled^2) +
    Curricular_units_2nd_sem_approved + I(Curricular_units_2nd_sem_approved^2) +
    Curricular_units_2nd_sem_grade + I(Curricular_units_2nd_sem_grade^2) +
    Unemployment_rate,
  data = data, family = gaussian()
)
summary(model_polinomic)
```

```{r}
residualPlot(model_polinomic)
```

```{r}
residualPlots(model_polinomic)
``` 



```{r}
library(car)
residualPlots(model_step)
```

```{r}
influencePlot(model = model_step)
```

```{r}
vif(model_step)
```


```{r}
anova(model, model_polinomic, test = "Chisq")
```

```{r}
summary(model_polinomic)
```


# Model 2 fit
```{r}
# Carreguem les dades
library(readr)
data <- read_csv("preprocessing/clean-data.csv")
```

```{r}
# Descriptiva previa de la variable a estudiar (Admission_grade)
summary(data$Curricular_units_2nd_sem_grade)
hist(data$Curricular_units_2nd_sem_grade)
```

```{r}
# Construim un mlgz sobre la variable a estudiar
model <- glm(Curricular_units_2nd_sem_grade ~ . - Target, data = data, family = gaussian())
summary(model)
```

```{r}
# Construim el model nul
model_nul <- glm(Curricular_units_2nd_sem_grade ~ 1, data = data, family = gaussian)

```

```{r}
# Comparem el nostre model complet amb el model nul
anova(model, model_nul, test = "Chisq")
```

```{r}
# Construim un model reduit, eliminant les variables poc significatives
model2 <- glm(
  Curricular_units_2nd_sem_grade ~ 
    Course + 
    Curricular_units_2nd_sem_credited + 
    Curricular_units_2nd_sem_enrolled + 
    Curricular_units_2nd_sem_evaluations + 
    Curricular_units_2nd_sem_approved + 
    Curricular_units_1st_sem_approved + 
    Curricular_units_1st_sem_grade + 
    Mother_s_occupation + 
    Admission_grade,
  data = data, family = gaussian
)
summary(model2)
```

```{r}
# Comparem el nou model amb el model nul, per veure si hi ha diferència significativa
anova(model, model2, test = "Chisq")
```

```{r}
# Comparem el nou model amb el model complet
anova(model, model2, test = "Chisq")
```

```{r}
# Afegim variables al model reduit (utilitzem la comanda step)
model_step <- step(model, direction = "both")
summary(model_step)
```

```{r}
# Comparem el model step amb el model complet
anova(model, model_step, test = "Chisq")
```

# Model 2 validation
```{r}
library(car)
residualPlot(model_step)
```

```{r}
library(car)
residualPlot(model_step)
```

```{r}
influencePlot(model = model_step)
```

```{r}
vif(model_step)
```

```{r}
# Seleccionar variables numèriques correlacionades
vars_pca <- data[, c(
  'Curricular_units_1st_sem_credited',
  'Curricular_units_1st_sem_enrolled',
  'Curricular_units_1st_sem_evaluations',
  'Curricular_units_1st_sem_approved',
  'Curricular_units_2nd_sem_approved',
  'Curricular_units_2nd_sem_grade',
  'Curricular_units_2nd_sem_enrolled'
)]
```

```{r}
# Fer PCA amb escalat
pca_result <- prcomp(vars_pca, center = TRUE, scale. = TRUE)

# Veure resum de variància explicada
summary(pca_result)
```

```{r}
model_polinomic <- glm(
  Curricular_units_2nd_sem_grade ~ 
    Course +
    Previous_qualification +
    Previous_qualification_grade +
    Admission_grade + I(Admission_grade^2) +
    Age_at_enrollment + I(Age_at_enrollment^2) +
    Curricular_units_1st_sem_credited + I(Curricular_units_1st_sem_credited^2) +
    Curricular_units_1st_sem_enrolled + I(Curricular_units_1st_sem_enrolled^2) +
    Curricular_units_1st_sem_evaluations + I(Curricular_units_1st_sem_evaluations^2) +
    Curricular_units_1st_sem_approved + I(Curricular_units_1st_sem_approved^2) +
    Curricular_units_2nd_sem_enrolled + I(Curricular_units_2nd_sem_enrolled^2) +
    Curricular_units_2nd_sem_approved + I(Curricular_units_2nd_sem_approved^2) +
    Curricular_units_2nd_sem_grade + I(Curricular_units_2nd_sem_grade^2) +
    Unemployment_rate,
  data = data, family = gaussian()
)
summary(model_polinomic)
```

```{r}
residualPlot(model_polinomic)
```

```{r}
residualPlots(model_polinomic)
``` 



```{r}
library(car)
residualPlots(model_step)
```

```{r}
influencePlot(model = model_step)
```

```{r}
vif(model_step)
```


```{r}
anova(model, model_polinomic, test = "Chisq")
```

```{r}
summary(model_polinomic)
```
